global class weatherObservation
    {
        global String weatherCondition{get;set;}
        global String clouds{get;set;}
        global String observation{get;set;}
        global Integer windDirection{get;set;}
        global String ICAO{get;set;}
        global Integer elevation{get;set;}
        global String countryCode{get;set;}
        global String cloudsCode{get;set;}
        global Double lng{get;set;}
        global String temperature{get;set;}
        global String dewPoint{get;set;}
        global String windSpeed{get;set;}
        global Integer humidity{get;set;}
        global String stationName{get;set;}
        global String datetime1{get;set;}
        global Double lat{get;set;}
        global Integer hectoPascAltimeter{get;set;}
    }